# Use a imagem oficial do LocalStack
FROM localstack/localstack

# Exponha as portas que o LocalStack utiliza
EXPOSE 4566 4510-4559

# Definir o comando para rodar o LocalStack
CMD ["localstack", "start"]